const shops = {
  vegetable: {
    category: '채소 · 청과',
    title: '영이네 채소가게',
    desc: '새벽 경매에서 직접 고른 싱싱한 채소. 할머니 손맛 나는 된장국용 나물도 함께.',
    hours: '06:00 – 18:00',
    accent: 'green',
    menu: [
      { name: '제철 채소 꾸러미', price: '8,000', tag: 'BEST' },
      { name: '쌈채소 세트', price: '5,000' },
      { name: '국거리 야채 팩', price: '4,500' },
      { name: '버섯 모듬 (300g)', price: '6,000' },
      { name: '고추·마늘 세트', price: '3,000' },
    ],
  },
  bunsik: {
    category: '분식 · 스트릿',
    title: '뽀까뽀까 가연분식',
    desc: '바삭한 튀김과 쫄깃한 떡볶이. 가연 언니의 비법 양념이 일품인 시장 속 분식집.',
    hours: '10:00 – 20:00',
    accent: 'red',
    menu: [
      { name: '뽀까뽀까 떡볶이', price: '5,500', tag: 'SIGNATURE' },
      { name: '치즈 튀김 모듬', price: '7,000' },
      { name: '참치 김밥', price: '4,000' },
      { name: '라볶이', price: '6,500' },
      { name: '오뎅국물 (리필)', price: '500' },
    ],
  },
  fruit: {
    category: '과일 · 청과',
    title: '싱싱 유정네 과일',
    desc: '유정 이모가 매일 아침 직접 골라내는 제철 과일. 당도 보장, 맛보기 한 조각 서비스.',
    hours: '07:00 – 19:00',
    accent: 'yellow',
    menu: [
      { name: '제철 과일 박스 (小)', price: '12,000', tag: 'SEASON' },
      { name: '컵 과일 (3종)', price: '5,000' },
      { name: '샤인머스캣 (송이)', price: '15,000' },
      { name: '방울토마토 (500g)', price: '4,000' },
      { name: '과일 주스 (수제)', price: '4,500' },
    ],
  },
  takoyaki: {
    category: '일식 · 스트릿',
    title: '타코야키 onmymic',
    desc: '마이크 앞에서 시작된 시장 속 타코야키. 겉은 바삭, 속은 촉촉한 반전 텍스처.',
    hours: '12:00 – 21:00',
    accent: 'navy',
    menu: [
      { name: '오리지널 타코야키 (8pc)', price: '6,000', tag: 'HOT' },
      { name: '치즈 폭탄 타코야키', price: '7,500' },
      { name: '문어 왕 타코야키', price: '8,000' },
      { name: '타코소스 감자', price: '4,500' },
      { name: '타코야키 + 음료 세트', price: '8,500' },
    ],
  },
  bungeoppang: {
    category: '간식 · 전통',
    title: '경은이네 붕빵붕빵',
    desc: '겨울이면 생각나는 붕어빵, 사계절 내내 따끈하게. 팥·슈크림·치즈 3종 맛.',
    hours: '11:00 – 20:00',
    accent: 'brown',
    menu: [
      { name: '팥 붕어빵 (5마리)', price: '3,000', tag: 'BEST' },
      { name: '슈크림 붕어빵 (5마리)', price: '3,500' },
      { name: '치즈 붕어빵 (5마리)', price: '3,500' },
      { name: '믹스 (10마리)', price: '6,000' },
      { name: '호떡 (1장)', price: '2,000' },
    ],
  },
  dalgona: {
    category: '디저트 · 수제',
    title: '달달 수제 달고나',
    desc: '직접 뽑는 수제 달고나와 추억의 뽑기. 아이들과 어른 모두 즐기는 달콤한 한 입.',
    hours: '11:00 – 19:00',
    accent: 'purple',
    menu: [
      { name: '수제 달고나', price: '2,000', tag: 'SIGNATURE' },
      { name: '달고나 라떼', price: '4,500' },
      { name: '뽑기 (1회)', price: '1,000' },
      { name: '달고나 선물 세트', price: '12,000' },
      { name: '말차 달고나', price: '2,500' },
    ],
  },
};
